language: python
env:
 - TOX_ENV=py27-django16
 - TOX_ENV=py27-django17
 - TOX_ENV=py27-django18
 - TOX_ENV=py27-django19
 - TOX_ENV=py34-django16
 - TOX_ENV=py34-django17
 - TOX_ENV=py34-django18
 - TOX_ENV=py34-django19
#- TOX_ENV=py35-django18
#- TOX_ENV=py35-django19
matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35-django18
        - TOX_ENV=py35-django19
install:
  - pip install tox 
script:
  - tox
